name: tik_tok_ui
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.8+2
  video_player: ^0.10.11+2
  amazon_cognito_identity_dart_2: ^0.1.14
  shared_preferences: ^0.5.7+3
  image_picker: ^0.6.7+4
  video_trimmer:

  cupertino_icons: ^0.1.3
  cached_network_image: ^2.0.0-rc

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: TikTokIcons
      fonts:
        - asset: assets/fonts/TikTokIcons.ttf
